// <auto-generated />
using CoffeeVendingMachine.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeVendingMachine.DataAccess.Migrations
{
    [DbContext(typeof(CoffeeVendingMachineDbContext))]
    [Migration("20230116211706_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeVendingMachine.Domain.Models.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoffeeTypeName")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Coffee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoffeeTypeName = 1,
                            Price = 15m
                        },
                        new
                        {
                            Id = 2,
                            CoffeeTypeName = 2,
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            CoffeeTypeName = 3,
                            Price = 25m
                        },
                        new
                        {
                            Id = 4,
                            CoffeeTypeName = 4,
                            Price = 25m
                        },
                        new
                        {
                            Id = 5,
                            CoffeeTypeName = 5,
                            Price = 30m
                        });
                });

            modelBuilder.Entity("CoffeeVendingMachine.Domain.Models.CoffeeIngridients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoffeeId")
                        .HasColumnType("int");

                    b.Property<int>("IngridientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoffeeId");

                    b.HasIndex("IngridientId");

                    b.ToTable("CoffeeIngridients");
                });

            modelBuilder.Entity("CoffeeVendingMachine.Domain.Models.Ingridients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Ingridients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Extra Sugar",
                            Price = 0f
                        },
                        new
                        {
                            Id = 2,
                            Name = "Creamer",
                            Price = 5f
                        },
                        new
                        {
                            Id = 3,
                            Name = "Caramelle",
                            Price = 5f
                        },
                        new
                        {
                            Id = 4,
                            Name = "Extra milk",
                            Price = 5f
                        });
                });

            modelBuilder.Entity("CoffeeVendingMachine.Domain.Models.CoffeeIngridients", b =>
                {
                    b.HasOne("CoffeeVendingMachine.Domain.Models.Ingridients", "Ingridients")
                        .WithMany("CharacteristicsName")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeVendingMachine.Domain.Models.Coffee", "Coffee")
                        .WithMany("CharacteristicsName")
                        .HasForeignKey("IngridientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffee");

                    b.Navigation("Ingridients");
                });

            modelBuilder.Entity("CoffeeVendingMachine.Domain.Models.Coffee", b =>
                {
                    b.Navigation("CharacteristicsName");
                });

            modelBuilder.Entity("CoffeeVendingMachine.Domain.Models.Ingridients", b =>
                {
                    b.Navigation("CharacteristicsName");
                });
#pragma warning restore 612, 618
        }
    }
}
